config/routes.rb
SampleApp::Application.routes.draw do
  root  'static_pages#home'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :jobs

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/job.rb
class Job < ActiveRecord::Base
	extend FriendlyId
	friendly_id :role, use: :slugged

	belongs_to :user
	default_scope -> { order('created_at DESC') }
	validates :employer, presence: true, length: { maximum: 140 }
	validates :role, presence: true, length: { maximum: 140 }
	validates :description, presence: true
	validates :criteria, presence: true
	validates :salary_type, presence: true
	validates :closed_date, presence: true
	validates :category, presence: true
	validates :apply, presence: true
	validates :user_id, presence: true
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create,:edit, :update,:destroy]
  before_action :correct_user,   only: :destroy
  
  def index
    @jobs = Job.all.paginate(page: params[:page] , :per_page => 20)
  end

  def new
    @job = Job.new
  end

  def show
    @job = Job.find_by_slug(params[:id])
  end

  def edit
    @job = Job.find_by_slug(params[:id])
  end

  def create
    @job = current_user.jobs.build(job_params)
    if @job.save
      flash[:success] = "Job posted!"
      redirect_to root_url
    else
      render 'jobs/new'
    end
  end

  def update
    @job = Job.find_by_slug(params[:id])
    if @job.update_attributes(job_params)
      flash[:success] = "Job updated"
      redirect_to @job
    else
      render 'edit'
    end
  end


  def destroy
    @job.destroy
    redirect_to root_url
  end

  private

  def job_params
    params.require(:job).permit!
  end

  def correct_user
    @job = current_user.jobs.find_by(id: params[:id])
    redirect_to root_url if @job.nil?
  end

  def permit!
    each_pair do |key, value|
      convert_hashes_to_parameters(key, value)
      self[key].permit! if self[key].respond_to? :permit!
    end

    @permitted = true
    self
  end
end

app/views/jobs/_job.html.erb
 <div class="col-md-3">
 	<h4 class="job-category"><%= job.category %></h4>
 	<a href="<%= job_path(job) %>">
 		<% if job.category == "Casual" %>
 		<button class="job-button casual-color">
 		<% elsif job.category == "Part-time" %>
 		<button class="job-button part-color">
 		<% else %>
 		<button class="job-button full-color">
 		<% end %>

 		<h4>
 			<strong><%= job.role %></strong>
 		</h4>
 		<p><%= job.employer %> - <%= job.location %></p>
 		<p>Posted <em><%= time_ago_in_words(job.created_at) %></em> ago.</p>
 		<p>Expired: <%= job.closed_date.strftime("%d/%m/%Y") %></p>
 		</button>
 	</a>

 <div class="social-likes social-likes_light" data-counters="no">

 	<div class="facebook" title="Share link on Facebook" data-url="http://cobaocab.herokuapp.com/jobs/<%= job.slug %>" data-title="<%= job.description %>"></div>
 	<div class="twitter" data-via="Coba_Ocab" data-related="Free job listing and sharing for students and new graduates" data-url="http://cobaocab.herokuapp.com/jobs/<%= job.slug %>" data-counters="no" data-title="<%= job.description %>" title="Share link on Twitter"></div>
 	<div class="plusone" data-url="http://cobaocab.herokuapp.com/jobs/<%= job.slug %>" data-counters="no"data-title="<%= job.description %>" title="Share link on Google+"></div>
 </div>
</div>

app/views/jobs/edit.html.erb
<% provide(:title, @job.role) %>
<h1><%= @job.role %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@job , :html => {:class => "form-horizontal"})  do |f| %>
    <%= render 'shared/error_messages', object: f.object%>

    <div class="form-group">
      <%= f.label :employer, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :employer,:placeholder =>"e.g: Google.inc", :required=>"required", :class =>"form-control"%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :location, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :location,:placeholder =>"e.g: Ultimo, Sydney, Australia", :required=>"required", :class =>"form-control"%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :role, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :role,:placeholder =>"e.g: Ruby on Rails web developer", :required=>"required", :class =>"form-control"%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_area :description, :placeholder =>"e.g: We are looking for a Ruby on rails programmer that will assist with the development of a data framework and storage solution for financial market data feeds. You may also be required to assist with the development of user interfaces.You will be working with other programmers and engineers on a truly collaborative and exciting project.", :required=>"required", :class =>"form-control", :rows => 10%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :criteria, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_area :criteria, :placeholder =>"e.g: I. Fifteen months web commercial development experience with ruby on rails II. ...", :required=>"required", :class =>"form-control", :rows => 10%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :category, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
       <select name="job[category]" id="job_role" class="form-control" required>
        <option value="Casual" <% if @job.category == "Casual" %>selected<% end %>>Casual</option> 
        <option value="Part-time" <% if @job.category == "Part-time" %>selected<% end %>>Part-time</option>
        <option value="Full-time" <% if @job.category  == "Full-time" %>selected<% end %>>Full-time</option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :salary_type, :class =>"col-sm-2 control-label" %>
    <div class="col-sm-6">
      <select name="job[salary_type]" id="salary_type" class="form-control" required>
        <option value="One-off" <% if @job.salary_type == "One-off" %>selected<% end %>>One-off</option> 
        <option value="Hourly" <% if @job.salary_type == "Hourly" %>selected<% end %>>Hourly</option>
        <option value="Anually" <% if @job.salary_type == "Anually" %>selected<% end %>>Anually</option>
        <option value="Stock option" <% if @job.salary_type == "Stock option" %>selected<% end %>>Stock option</option>
        <option value="Discussed in confidentiality" <% if @job.salary_type == "Discussed in confidentiality" %>selected<% end %>>Discussed in confidentiality</option>
        <option value="Volunteer" <% if @job.salary_type == "Volunteer" %>selected<% end %>>Volunteer</option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :salary_amount, :class =>"col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :salary, :placeholder =>"e.g: 30000", :class =>"form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :closed_date, :class =>"col-sm-2 control-label" %>
    <div class='input-group col-sm-5' id='datetimepicker5'>
      <input name="job[closed_date]"type='text' class="form-control" data-format="DD/MM/YYYY" placeholder="DD/MM/YYYY format. e.g 25-9-2014" required="required" value="<%= @job.closed_date.strftime("%d/%m/%Y") %>"/>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-time">
        </span>
      </span>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :how_to_apply, :class =>"col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_area :apply, :required=>"required", :class =>"form-control", :rows => 10%>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-2">
     <%= f.submit "Update", class: "btn btn-primary" %>
   </div>
 </div>


 <script type="text/javascript">
 $(function () {
  $('#datetimepicker5').datetimepicker({
    pickTime: false
  });
});
 </script>

 <% end %>
</div>
</div>

app/views/jobs/index.html.erb
<div class="row">
	<div class="col-md-12">
		<h1> Open position</h1>
		<%= render @jobs %>
	</div>
</div>
<%= will_paginate @jobs, renderer: BootstrapPagination::Rails %>

app/views/jobs/new.html.erb
<% provide(:title, 'Post a job') %>
<h1>Post a job</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@job , :html => {:class => "form-horizontal"})  do |f| %>
    <%= render 'shared/error_messages', object: f.object%>

    <div class="form-group">
      <%= f.label :employer, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :employer,:placeholder =>"e.g: Google.inc", :required=>"required", :class =>"form-control"%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :location, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :location,:placeholder =>"e.g: Ultimo, Sydney, Australia", :required=>"required", :class =>"form-control"%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :role, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_field :role,:placeholder =>"e.g: Ruby on Rails web developer", :required=>"required", :class =>"form-control"%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :description, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_area :description, :placeholder =>"e.g: We are looking for a Ruby on rails programmer that will assist with the development of a data framework and storage solution for financial market data feeds. You may also be required to assist with the development of user interfaces.You will be working with other programmers and engineers on a truly collaborative and exciting project.", :required=>"required", :class =>"form-control", :rows => 10%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :criteria, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <%= f.text_area :criteria, :placeholder =>"e.g: I. Fifteen months web commercial development experience with ruby on rails II. ...", :required=>"required", :class =>"form-control", :rows => 10%>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :category, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
       <select name="job[category]" id="job_role" class="form-control" required>
        <option value="" default selected>Select the job category</option>
        <option value="Casual">Casual</option> 
        <option value="Part-time">Part-time</option>
        <option value="Full-time">Full-time</option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :salary_type, :class =>"col-sm-2 control-label" %>
    <div class="col-sm-6">
      <select name="job[salary_type]" id="salary_type" class="form-control" required>
        <option value="" default selected>Select the salary type</option>
        <option value="One-off">One-off</option> 
        <option value="Hourly">Hourly</option>
        <option value="Anually">Anually</option>
        <option value="Stock option">Stock option</option>
        <option value="Discussed in confidentiality">Discussed in confidentiality</option>
        <option value="volunteer">Volunteer</option>
      </select>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :salary_amount, :class =>"col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_field :salary, :placeholder =>"e.g: 30000", :class =>"form-control"%>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :closed_date, :class =>"col-sm-2 control-label" %>
    <div class='input-group col-sm-5' id='datetimepicker5'>
      <input name="job[closed_date]"type='text' class="form-control" data-format="DD/MM/YYYY" placeholder="DD/MM/YYYY format. e.g 25-9-2014" required="required"/>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-time">
        </span>
      </span>
    </div>
  </div>

  
  <div class="form-group">
    <%= f.label :how_to_apply, :class =>"col-sm-2 control-label" %>
    <div class="col-sm-6">
      <%= f.text_area :apply, :placeholder =>"Please explain the process on how the candidate could apply for the position", :required=>"required", :class =>"form-control", :rows => 10%>
    </div>
  </div>


  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-2">
     <%= f.submit "Post this job", class: "btn btn-primary" %>
   </div>
 </div>


 <script type="text/javascript">
 $(function () {
  $('#datetimepicker5').datetimepicker({
    pickTime: false
  });
});
 </script>

 <% end %>
</div>
</div>

app/views/jobs/show.html.erb
<% provide(:title, @job.role) %>
<h1><%= @job.role %></h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@job , :html => {:class => "form-horizontal"})  do |f| %>
    <%= render 'shared/error_messages', object: f.object%>

    <div class="form-group">
      <%= f.label :employer, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <p class="form-control-static"><%= @job.employer %> </p>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :location, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
        <p class="form-control-static"><%= @job.location %> </p>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :role, :class =>"col-sm-2 control-label" %>
      <div class="col-sm-6">
       <p class="form-control-static"><%= @job.role %> </p>
     </div>
   </div>

   <div class="form-group">
    <%= f.label :description, :class =>"col-sm-2 control-label" %>
    <div class="col-sm-6">
     <p class="form-control-static"><%= simple_format @job.description %> </p>
   </div>
 </div>

 <div class="form-group">
  <%= f.label :criteria, :class =>"col-sm-2 control-label" %>
  <div class="col-sm-6">
   <p class="form-control-static"><%= simple_format @job.criteria %> </p>
 </div>
</div>

<div class="form-group">
  <%= f.label :category, :class =>"col-sm-2 control-label" %>
  <div class="col-sm-6">
    <p class="form-control-static"><%= @job.category %> </p>
  </div>
</div>

<div class="form-group">
  <%= f.label :salary, :class =>"col-sm-2 control-label" %>
  <div class="col-sm-6"> 
    <p class="form-control-static">
      <% if !@job.salary.nil? %>
      $<%= @job.salary %> 
      <% end %> 
      <%= @job.salary_type %> 
    </p>
  </div>
</div>

<div class="form-group">
  <%= f.label :closed_date, :class =>"col-sm-2 control-label" %>
  <div class='input-group col-sm-5' id='datetimepicker5'>
   <p class="form-control-static"><%= @job.closed_date.strftime("%d/%m/%Y") %></p>
 </div>
</div>

<div class="form-group">
  <%= f.label :how_to_apply, :class =>"col-sm-2 control-label" %>
  <div class="col-sm-6">
   <p class="form-control-static"><%= simple_format @job.apply %> </p>
 </div>
</div>


<div class="form-group">
  <div class="col-sm-offset-2 col-sm-2">
    <% if current_user?(@job.user) %>
    <%= link_to "Edit", edit_job_path(@job),:class=>"btn btn-primary"%>
    <%= link_to "Delete", @job, method: :delete,
    data: { confirm: "Are you sure you want to remove this job from the list?" },
    title: @job.role, :class=>"btn btn-danger" %>
    <% end %>
  </div>
</div>

<div class="form-group">
  <%= f.label :share, :class =>"col-sm-2 control-label" %>
  <div class="col-sm-6">
    <div class="social-likes" data-counters="no">
      <div class="facebook" title="Share link on Facebook">Facebook</div>
      <div class="twitter" data-via="Coba_Ocab" data-related="Free job listing and sharing for students and new graduates" title="Share link on Twitter">Twitter</div>
      <div class="plusone" title="Share link on Google+">Google+</div>
    </div>
  </div>
</div>


<% end %>
</div>
</div>