config/routes.rb
SampleApp::Application.routes.draw do
  root  'static_pages#home'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :jobs

  match '/signup',  to: 'users#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">

	<div class="row">
		<div class="col-md-12">
			©Kevin Aditya 2014 - Any feedback please send to : <a href="mailto:cobaocab@gmail.com">cobaocab@gmail.com</a>
			<div class="fb-like pull-right" data-href="https://www.facebook.com/thecobaocab" data-layout="standard" data-action="like" data-show-faces="true" data-share="true"></div>
		</div>

		<!-- <div class="col-md-1 col-xs-2">

		<form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
			<input type="hidden" name="cmd" value="_s-xclick">
			<input type="hidden" name="hosted_button_id" value="LGBS7FHK5VHPY">
			<input height="5%", width="100px" type="image" src="https://www.sandbox.paypal.com/en_AU/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal — The safer, easier way to pay online.">
			<img alt="" border="0" src="https://www.sandbox.paypal.com/en_AU/i/scr/pixel.gif" width="1" height="1">
		</form>
	</div> -->

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse" role="banner">
  <div class="container">
    <div class="navbar-header">
      <button class="navbar-toggle collapsed" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= image_tag "logo3.png", id: "logo2" %><%= link_to "CobaOcab", root_path, id: "logo" %>
    </div>
    <nav style="height: 0.8px;" class="navbar-collapse bs-navbar-collapse collapse" role="navigation">
      <ul class="nav navbar-nav">
        <li><%= link_to "Post a job", new_job_path %></li>
       <li><%= link_to "Seek a job", jobs_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
       <li><%= link_to "Home", root_path %></li>
       <% if signed_in? %>
       <li id="fat-menu" class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          Account <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li><%= link_to "Profile", current_user %></li>
          <li><%= link_to "Settings", edit_user_path(current_user) %></li>
          <li class="divider"></li>
          <li>
            <%= link_to "Sign out", signout_path, method: "delete" %>
          </li>
        </ul>
      </li>
      <% else %>
      <li><%= link_to "Sign in", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</div>
</header>

<!-- <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
      <nav>
        <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "Users", users_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>
-->
<!-- <div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
            <%= link_to image_tag("http://getdocit.com/logo.png", alt: "GetDocit", id:"logos"), root_path %>
        </div>
        <div class="collapse navbar-collapse pull-right">
          <ul class="nav navbar-nav">
            <li><a href="#" data-toggle="modal" data-target="#register">Register</a></li>
            <li><a href="#about" data-toggle="modal" data-target="#login">Login</a></li>
          </ul>
        </div><!--/.nav-collapse
      </div>
    </div> -->

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= favicon_link_tag 'favicon.ico' %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="og:title" content="<%= yield(:title).present? ? yield(:title) : 'CobaOcab' %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= request.url %>" />
  <meta property="og:image" content="https://cobaocab.herokuapp.com/assets/logo4-203d6dfe95ae0f45296e2c2400ad7028.png" />
  <meta property="og:site_name" content="Cobaocab" />
  <meta property="og:description" content="CobaOcab, a place to list jobs for students and new graduates. Get employed and help others to get a job by sharing the job advertisement to social media or post a new job advertisement here for FREE!" />
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag "application", media: "all",
  "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>
  <div id="fb-root"></div>
  <script>(function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=439517296145888";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));</script>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>